SAT/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^$', 'app.views.muestra', name='muestra'),
    # url(r'^SAT/', include('SAT.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),

     # Url exitoso
     url(r'^login/$',  login),
     url(r'^logout/', 'app.views.logout_view', name = 'logout_view'),
     url(r'^success/$', 'app.views.success', name='success_muestra'),
     
     # Urls para el manejo de estudiantes.
     url(r'^estudiante/$', 'app.views.estudiante', name='estudiante'),
     url(r'^alta_estudiante/$', 'app.views.alta_estudiante', name='alta_estudiante'),
     url(r'^edita_estudiante/(\d+)/$', 'app.views.edita_estudiante', name='edita_estudiante'),
     url(r'^perfil_estudiante/(\d+)/$', 'app.views.perfil_estudiante', name='perfil_estudiante'),
     url(r'^evaluar_estudiante/(\d+)/$', 'app.views.evaluar_estudiante', name='evaluar_estudiante'),

     # Urls para el manejo de muestras.
     url(r'^muestra/$', 'app.views.muestra', name='muestra'),
     url(r'^seleccion_muestra/$', 'app.views.seleccion_muestra', name='seleccion_muestra'),
     url(r'^perfil_muestra/(\d+)/$', 'app.views.perfil_muestra', name='perfil_muestra'),
     url(r'^alta_muestra/$', 'app.views.alta_muestra', name='alta_muestra'),
     url(r'^eliminar_muestra/(\d+)/$', 'app.views.eliminar_muestra', name='eliminar_muestra'),
     
     # Url para crear cartas de notificacion
     # url(r'^carta_notificacion/(?P<string>[\w\-]+)', 'app.views.obtener_carta', name='obtener_carta'),
     url(r'^carta_notificacion/(\d+)/(\d+)/$', 'app.views.obtener_carta', name='obtener_carta'),
     
     # Urls para iniciar y cerrar sesion.
     url(r'^accounts/login/$',  login),
     url(r'^accounts/logout/$',  logout),
     
     # Urls para mostrar vista de encuesta.
     url(r'^autenticacion_encuesta/$', 'app.views.autenticacion_encuesta', name='autenticacion_encuesta'),
     url(r'^aplicacion_encuesta/(\w+)/$', 'app.views.aplicacion_encuesta', name='aplicacion_encuesta'),
     # url(r'^encuesta_agradecimiento/$', 'app.views.encuesta_agradecimiento', name='encuesta_agradecimiento'),
     
     # Urls para mostrar lista de encuestas contestadas.
     url(r'^encuestas_contestadas/$', 'app.views.encuestas_contestadas', name='encuestas_contestadas'),
     url(r'^revisar_encuesta/(\d+)/$', 'app.views.revisar_encuesta', name='revisar_encuesta'),

     # Urls para mostrar reportes en highcharts.
     url(r'^reportes/$', 'app.views.reportes', name='reportes'),
     
     # Url para subir el CSV
     url(r'^subir_csv/$', 'app.views.subir_csv', name='subir_csv'),
     url(r'^subir_csv/success/$', 'app.views.subir_csv_success', name='subir_csv_success'),
)

# Add the static files pattern to the url.
urlpatterns += staticfiles_urlpatterns()

app/models.py
from django.db import models
from datetime import date
#from django import forms

# Create your models here.
class Padre(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(null=False, max_length=255)
    apellido = models.CharField(null=False, max_length=255)
    correo = models.CharField(null=True, max_length=255)
    telefono = models.CharField(null=True, max_length=255)
    celular = models.CharField(null=True, max_length=255)
      
class Estudiante(models.Model):
    matricula = models.IntegerField(primary_key=True)
    nombre = models.CharField(null=False, max_length=255)
    apellido = models.CharField(null=False, max_length=255)
    correo = models.CharField(null=True, max_length=255)
    telefono = models.CharField(null=True, max_length=255)
    celular = models.CharField(null=True, max_length=255)
    padre = models.ForeignKey(Padre,null=True,related_name='Padre N/D')
    madre = models.ForeignKey(Padre,null=True,related_name='Madre N/D')
    color = models.IntegerField(null=True, max_length=255)
    estado_institucion = models.IntegerField(null=True, max_length=255) 
    
class Clase(models.Model):
    id = models.AutoField(primary_key=True, max_length=255)
    clave_materia = models.CharField(null=False, max_length=255)
    nombre = models.CharField(null=False, max_length=255)
    
class Grupo(models.Model):
    crn = models.IntegerField(primary_key=True,null=False, max_length=255)
    clase = models.ForeignKey(Clase, null=False)
    horario_1 = models.CharField(null=True, max_length=255)
    horario_2 = models.CharField(null=True, max_length=255)
    horario_3 = models.CharField(null=True, max_length=255)
    horario_4 = models.CharField(null=True, max_length=255)
    horario_5 = models.CharField(null=True, max_length=255)
    horario_6 = models.CharField(null=True, max_length=255)
    anio = models.IntegerField(null=True, max_length=255)
    semestre = models.IntegerField(null=True, max_length=255)
    profesor = models.CharField(null=False, max_length=255)
    
class Inscrito(models.Model):
    id = models.AutoField(primary_key=True)
    estudiante = models.ForeignKey(Estudiante, null=False)
    grupo = models.ForeignKey(Grupo, null=False)
    
class Antidoping(models.Model):
    id =  models.AutoField(primary_key=True)
    nombre = models.CharField(null=False, max_length=255)
    dia = models.CharField(default='', null=False, max_length=255)
    muestra_inicio = models.CharField(default='', null=False, max_length=255)
    muestra_fin = models.CharField(default='', null=False, max_length=255)
    antidoping_inicio = models.DateField(default=date.today)
    antidoping_fin = models.DateField(null=True,max_length=255)
    estado_antidoping = models.IntegerField(null=True, max_length=255)
    notas = models.CharField(null=False, max_length=255)
    
class EstudianteMuestra(models.Model):
    id = models.AutoField(primary_key=True)
    inscrito = models.ForeignKey(Inscrito,null=False)
    antidoping = models.ForeignKey(Antidoping,null=False)
    folio = models.CharField(null=False, max_length=255)
    tipo_seleccion = models.IntegerField(null=True, max_length=255)
    resultado = models.IntegerField(null=True, max_length=255)
    tipo_droga = models.CharField(null=True, max_length=255)
    estado = models.IntegerField(null=True, max_length=255)
    notas = models.CharField(null=True, max_length=255)
    respuestas = models.TextField(null=True)

app/forms.py
# -*- coding: utf-8 -*
from app.models import *
from django import forms
from django.forms import ModelForm 
from crispy_forms.helper import FormHelper,reverse
from crispy_forms.layout import *

my_default_errors = {
    'required': 'Se requiere este campo.',
    'invalid': 'Este campo es invalido.'
}

ESTADO_INSTITUCION = (
    ('0','Activo'),
    ('1','Inactivo'),
)

TIPO_SELECCION = (
    ('0','Aleatoria'),
    ('1','Dirigida'),
)

TIPO_DROGA = (
    ('0', 'Marihuana'),
    ('1', 'Cocaína'),
    ('2', 'Metanfetaminas | Anfetaminas'),
    ('3', 'Alucinógenos'),
    ('4', 'Opiáceos'),
    ('5', 'Otro'),
)

ESTADO_ANTIDOPING = (
    ('0','Iniciado'),
    ('1','1era. Notificación recibida'),
    ('2','2da. Notificación recibida'),
    ('3','Encuesta realizada'),
    ('4','Prueba realizada'),
    ('5','Cerrado'),
)

SI_NO = (
    ('0','Sí'),
    ('1','No'),
)

ALCOHOL_FRECUENCIA = (
    ('0','No consumo'),
    ('1','Una vez a la semana o menos'),
    ('2','Dos veces a la semana'),
    ('3','Más de dos veces por semana'),
)

TABACO_FRECUENCIA = (
    ('0','No consumo'),
    ('1','Menos de 5 cigarros al día'),
    ('2','De 5 a 10 cigarros al día'),
    ('3','De 10 cigarrillos a una cajetilla al día'),
    ('4','Más de una cajetilla al día'),
)

SI_NO_2 = (
    ('0','Sí'),
    ('1','No (Pasa a la pregunta 8)'),
)

QUIEN_OFRECIDO = (
    ('0','Un compañero de la escuela'),
    ('1','Un amigo'),
    ('2','Un vecino'),
    ('3','Un conocido'),
    ('4','Un familiar'),
    ('5','Otro'),
)

DONDE_OFRECIDO = (
    ('0','En un antro, bar, concierto o fiesta'),
    ('1','En un viaje al extranjero'),
    ('2','En casa de algún amigo o compañero'),
    ('3','En la escuela'),
    ('4','En la calle'),
    ('5','Otro'),
)

QUE_OFRECIDO_CONSUMIDO = (
    ('0','Marihuana'),
    ('1','Cocaína'),
    ('2','Anfetaminas, Metanfetaminas'),
    ('3','Alucinógenos'),
    ('4','Opiáceos'),
    ('5','Otro'),
)

SI_NO_3 = (
    ('0','Sí'),
    ('1','No (Pasa a la pregunta 13)'),
)

ULTIMO_CONSUMIDO = (
    ('0','En los últimos 30 días'),
    ('1','Hace más de un mes y menos de cinco meses'),
    ('2','Hace más de seis meses'),
)

QUIEN_OFRECIDO = (
    ('0','Un compañero de la escuela'),
    ('1','Un amigo'),
    ('2','Un vecino'),
    ('3','Un conocido'),
    ('4','Un familiar'),
    ('5','Otro'),
)

LUGAR_CONSUMIDO = (
    ('0','En un antro, bar, concierto o fiesta'),
    ('1','En un viaje al extranjero'),
    ('2','En casa de algún amigo o compañero'),
    ('3','En la escuela'),
    ('4','En la calle'),
    ('5','Otro'),
)

COLOR = (
    # ('0','Gris'),
    ('1','Verde'),
    ('2','Amarillo'),
    ('3','Naranja'),
    ('4','Rojo'),
    ('5','Negro'),
)

DIA_SEMANA = (
    ('lunes', 'Lunes'),
    ('martes', 'Martes'),
    ('miercoles', 'Miércoles'),
    ('jueves', 'Jueves'),
    ('viernes', 'Viernes'),
    ('sabado', 'Sábado'),
  )

HORARIO = (
    ('7', '7:00'),
    ('7+', '7:30'),
    ('8', '8:00'),
    ('8+', '8:30'),
    ('9', '9:00'),
    ('9+', '9:30'),
    ('10', '10:00'),
    ('10+', '10:30'),
    ('11', '11:00'),
    ('11+', '11:30'),
    ('12', '12:00'),
    ('12+', '12:30'),
    ('13', '13:00'),
    ('13+', '13:30'),
    ('14', '14:00'),
    ('14+', '14:30'),
    ('15', '15:00'),
    ('15+', '15:30'),
    ('16', '16:00'),
    ('16+', '16:30'),
    ('17', '17:00'),
    ('17+', '17:30'),
    ('18', '18:00'),
    ('18+', '18:30'),
    ('19', '19:00'),
    ('19+', '19:30'),
    ('20', '20:00'),
    ('20+', '20:30'),
    ('21', '21:00'),
    ('21+', '21:30'),
    ('22', '22:00'),
  )

RESULTADO_ANTIDOPING = (
    ('0', 'Negativo'),
    ('1', 'Positivo'),
  )

class AltaEstudiante(ModelForm):
  matricula = forms.DecimalField(required = True,label="Matricula")
  nombre = forms.CharField(error_messages=my_default_errors,label="Nombre",required=True)
  apellido = forms.CharField(error_messages=my_default_errors,label="Apellido",required=True)
  correo = forms.CharField(error_messages=my_default_errors,label="Correo",required=False)
  telefono = forms.CharField(required = False,label="Telefono")
  celular = forms.CharField(required = False,label="Celular")
  color = forms.ChoiceField(error_messages=my_default_errors,choices=COLOR)
  estado_institucion = forms.ChoiceField(error_messages=my_default_errors,choices=ESTADO_INSTITUCION)
  
  class Meta:
    model = Estudiante
    exclude = ('padre','madre')
        
  def __init__(self, *args, **kwargs):
      self.helper = FormHelper()
      self.helper.form_id = 'id-AltaEstudiante'
      self.helper.form_class = 'blueForms'
      self.helper.form_method = 'POST'
      self.helper.layout = Layout(
	Div(
	Div(
	    'matricula',
	    'nombre',
	    'apellido',
	    'correo',
	    'telefono',
	    'celular',
	    css_class='span3'),
	Div('color',
	    'estado_institucion',
	    css_class='span3'),css_class='row-fluid'),
	ButtonHolder(
	    Submit('submit', 'Crear', css_class='btn-success')
	))
      super(AltaEstudiante, self).__init__(*args, **kwargs)
  
class CrearAntidoping(ModelForm):
  nombre = forms.CharField(error_messages=my_default_errors,label="Nombre")
  tamano_muestra = forms.DecimalField(label="Tamaño de la muestra (máximo)")
  notas = forms.CharField(widget=forms.Textarea, error_messages=my_default_errors, label="Notas", required=False)
  seleccion_alumnos = forms.CharField(widget=forms.Textarea, required=False, label="Selección de alumnos")
  seleccion_grupos = forms.CharField(widget=forms.Textarea, required=False, label="Selección de grupos")
  dia = forms.ChoiceField(error_messages=my_default_errors,choices=DIA_SEMANA, label="Día")
  inicio = forms.ChoiceField(error_messages=my_default_errors,choices=HORARIO)
  fin = forms.ChoiceField(error_messages=my_default_errors,choices=HORARIO)
  
  class Meta:
    model = Antidoping
    exclude = ('muestra_inicio', 'antidoping_inicio', 'antidoping_fin', 'muestra_fin', 'estudianteMuestra', 'estado_antidoping')
        
  def __init__(self, *args, **kwargs):
      self.helper = FormHelper()
      self.helper.form_id = 'id-CrearAntidoping'
      self.helper.form_class = 'blueForms'
      self.helper.form_method = 'POST'
      self.helper.form_action = 'seleccion_muestra'
      self.helper.layout = Layout(
	Div(
	Div(
	    'nombre',
      'tamano_muestra',
      'dia',
      'seleccion_alumnos',
	    css_class='span3'
      ),
	Div(
      'inicio',
      'fin',
	    css_class='span3'
      ),
	Div(
	    'notas',
	    'seleccion_grupos',
	    css_class='span3'),css_class='row-fluid'),
	ButtonHolder(
	    Submit('submit', 'Crear', css_class='btn-success')
	))
      super(CrearAntidoping, self).__init__(*args, **kwargs)

# Esta forma se encarga de evaluar el resultado estudiante para cada antidoping.

class EvaluaEstudiante(ModelForm):
  tipo_droga = forms.MultipleChoiceField(required = False, widget=forms.CheckboxSelectMultiple, choices=TIPO_DROGA)
  estado = forms.ChoiceField(required = False, error_messages=my_default_errors,choices=ESTADO_ANTIDOPING)
  tipo_seleccion = forms.ChoiceField(required = False, error_messages=my_default_errors,choices=TIPO_SELECCION)
  resultado = forms.ChoiceField(required = False, error_messages=my_default_errors,choices=RESULTADO_ANTIDOPING)
  notas = forms.CharField(required = False, widget=forms.Textarea, error_messages=my_default_errors, label="Notas")

  class Meta:
    model = EstudianteMuestra
    exclude = ('folio','antidoping','inscrito','respuestas')
        
  def __init__(self, *args, **kwargs):
      self.helper = FormHelper()
      self.helper.form_id = 'id-EvaluaEstudiante'
      self.helper.form_class = 'blueForms'
      self.helper.form_method = 'POST'
      self.helper.form_action = ''
      self.helper.layout = Layout(
  Div(
  Div(
      'notificacion',
      'tipo_droga',
      css_class='span3'),
  Div(
      'tipo_seleccion',
      'estado',
      'resultado',
      css_class='span3'),
  Div(
      'notas',
      css_class='span3'),css_class='row-fluid'),
  ButtonHolder(
      Submit('submit', 'Guardar', css_class='btn-success')
  ))
      super(EvaluaEstudiante, self).__init__(*args, **kwargs)

class AplicacionEncuesta(ModelForm):
  folio = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}), error_messages=my_default_errors, label="Folio", required=False)
  medicamento_consumido = forms.ChoiceField(widget=forms.RadioSelect(), choices=SI_NO, label="1. ¿Actualmente consumes algún medicamento?",required=False)
  medicamento_consumido_paraque = forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'cols':40}), label="Si respondiste 'Sí', ¿cuál y para qué?", required = False)
  alcohol_frecuencia = forms.ChoiceField(widget=forms.RadioSelect(), choices=ALCOHOL_FRECUENCIA, label="2. ¿Con qué frecuencia consumes bebidas alcohólicas?",required=False)
  tabaco_frecuencia = forms.ChoiceField(widget=forms.RadioSelect(), choices=TABACO_FRECUENCIA, label="3. ¿Con qué frecuencia consumes cigarros de tabaco?",required=False)
  droga_ofrecido = forms.ChoiceField(widget=forms.RadioSelect(), choices=SI_NO_2, label="4. ¿Ten han ofrecido alguna vez alguna droga ilegal?",required=False)
  quien_ofrecido = forms.ChoiceField(widget=forms.RadioSelect(), choices=QUIEN_OFRECIDO, label="5. ¿Quién te ha ofrecido?",required=False)
  quien_ofrecido_otro = forms.CharField(widget=forms.TextInput(), label="Si responsite 'Otro' especifica quién", required=False)
  donde_ofrecido = forms.ChoiceField(widget=forms.RadioSelect(), choices=DONDE_OFRECIDO, label="6. ¿En dónde te han ofrecido?",required=False)
  donde_ofrecido_otro = forms.CharField(widget=forms.TextInput(), label="Si responsite 'Otro' especifica dónde", required=False)  
  que_ofrecido = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=QUE_OFRECIDO_CONSUMIDO, label="7. ¿Qué te ofrecieron? (Puedes seleccionar más de una opción)", required = False)
  que_ofrecido_otro = forms.CharField(widget=forms.TextInput(), label="Si responsite 'Otro' especifica qué", required=False)

templates/encuestas/autenticacion.html
{% extends "registration/base.html" %}

{% block style %}{% endblock %}

{% block script %}{% endblock %}

{% block content %}

    <div class="container">
        {% if existe_respuesta %}
            <center><p>La encuesta con el folio que se introdujo ya fue contestada.</p></center>
        {% elif no_existe_folio %}
            <center><p>El folio es incorrecto.</p></center>
        {% else %}
            <center><p></p></center>
        {% endif %}
        
        <form class="form-signin" method="POST" action="/autenticacion_encuesta/" > {% csrf_token %}
            <center><h2 class="form-signin-heading">Iniciar Encuesta</h2></center>
            <input type="text" name="folio" class="input-block-level" placeholder="Folio">
            <center><button class="btn btn-large btn-primary" type="submit">Entrar</button></center>
            <input type="hidden" name="next" value="{{ next|escape }}" />
        </form>
    </div> <!-- /container -->

{% endblock %}

templates/encuestas/encuesta.html
{% extends "registration/base.html" %}
{% load crispy_forms_tags %}

{% block style %}
<link href="{{ STATIC_URL }}CSS/tag-it.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}CSS/jquery.tagsinput.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block script %}
<script src="{{ STATIC_URL }}JS/jquery-1.9.1.min.js"></script>
<script src="{{ STATIC_URL }}JS/jquery-ui-1.10.1.custom.js" type="text/javascript" charset="utf-8"></script>
<script src="{{ STATIC_URL }}JS/jquery.tagsinput.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block content %}
 
<div class="container">
 	<div class="hero-unit">
      <h2>Revisa que tu información sea la correcta</h2>
        <p>Nombre: <strong>{{estudiante.nombre}} {{estudiante.apellido}} </strong><br>
           Matrícula: <b>{{estudiante.matricula}}</b></p>
        <p><i>En caso de existir un error en la información, favor de avisar al personal del CAT.</i></p>
    </div>

      <!-- Main hero unit for a primary marketing message or call to action -->
	<div class="hero-unit">
		<h3>Encuesta del CAT </h3>
		{{ forma.errors }}
		{% crispy forma %}       	
	</div>
  <hr>
</div> <!-- /container -->
 
 {% endblock %}

templates/encuestas/encuesta_agradecimiento.html
{% extends "registration/base.html" %}
{% load crispy_forms_tags %}

{% block style %}
<link href="{{ STATIC_URL }}CSS/tag-it.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}CSS/jquery.tagsinput.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block script %}
<script src="{{ STATIC_URL }}JS/jquery-1.9.1.min.js"></script>
<script src="{{ STATIC_URL }}JS/jquery-ui-1.10.1.custom.js" type="text/javascript" charset="utf-8"></script>
<script src="{{ STATIC_URL }}JS/jquery.tagsinput.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block content %}
 
 <div class="container">
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
       <center>
       <h3>¡Tu encuesta ha sido registrada!</h3>
       <h3>Pasa a entregar el Ipad para continuar</h3>
       <h3>Gracias y que tengas excelente día</h3>
       <a href="/autenticacion_encuesta/"><input type="button" class="btn btn-primary" value="OK"></button></a>
       </center>
      </div>
      <hr>
    </div> <!-- /container -->
 
 {% endblock %}

templates/encuestas/encuesta_estudiante.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

 {% block style %}
 
 <link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
 {% endblock %}
 
 {% block script %}
 
 <script src="{{ STATIC_URL }}JS/jquery-1.9.1.min.js"></script>
 <script src="{{ STATIC_URL }}JS/jquery-ui-1.10.1.custom.js" type="text/javascript" charset="utf-8"></script>
 
 <script type="text/javascript">
    $(document).ready(function() {
      $('#id_nombres').attr('readonly', true);
      $('#id_apellidos').attr('readonly', true);
      $('#id_matricula').attr('readonly', true);
      $('#id_correo').attr('readonly', true);
      $('#id_semestre').attr('readonly', true);
      $('#id_opinion').attr('readonly', true);
      $('#id_frecuencia').attr('readonly', true);
    });
  </script>
 
 {% endblock %}
 
 {% block content %}
 
 <div class="container">
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
       <h3>Revisar Encuesta</h3>
        {{ forma.errors }}
       	{% crispy forma %}       	
      </div>
      <hr>
    </div> <!-- /container -->
 
 {% endblock %}

templates/encuestas/encuestas.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

 {% block style %}
 
 <link href="{{ STATIC_URL }}CSS/tag-it.css" rel="stylesheet" type="text/css">
 <link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
 <link href="{{ STATIC_URL }}CSS/jquery.tagsinput.css" rel="stylesheet" type="text/css">
  <style type="text/css">
  #icons{
    float:right;
  }
 </style>
 
 {% endblock %}
 
 {% block script %}
 
 <script src="{{ STATIC_URL }}JS/jquery-1.9.1.min.js"></script>
 <script src="{{ STATIC_URL }}JS/jquery-ui-1.10.1.custom.js" type="text/javascript" charset="utf-8"></script>
 <script src="{{ STATIC_URL }}JS/jquery.tagsinput.js" type="text/javascript" charset="utf-8"></script>
 
 {% endblock %}
 
 {% block content %}
 
 <div class="container">
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
      <table class="table table-hover">
      <tr>
      <th>#</th>
        <th>Folio</th>
      </tr>
      {% for e in encuestas %}
      <tr>
      <td>{{e.id}}
	<div id="icons">
	  <a href="/revisar_encuesta/{{e.id}}">
	    <i class="icon-search"></i>
	  </a>
	</div>
	</td>
      <td>{{e.folio}}</td>
      </tr>
      {% endfor %}
      <table>
      </div>
      <hr>
    </div> <!-- /container -->
 
 {% endblock %}

templates/encuestas/encuestas_contestadas.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

 {% block style %}
 
 <link href="{{ STATIC_URL }}CSS/tag-it.css" rel="stylesheet" type="text/css">
 <link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
 <link href="{{ STATIC_URL }}CSS/jquery.tagsinput.css" rel="stylesheet" type="text/css">
  <style type="text/css">
  #icons{
    float:right;
  }
 </style>
 
 {% endblock %}
 
 {% block script %}
 
 <script src="{{ STATIC_URL }}JS/jquery-1.9.1.min.js"></script>
 <script src="{{ STATIC_URL }}JS/jquery-ui-1.10.1.custom.js" type="text/javascript" charset="utf-8"></script>
 <script src="{{ STATIC_URL }}JS/jquery.tagsinput.js" type="text/javascript" charset="utf-8"></script>
 
 {% endblock %}
 
 {% block content %}
 
 <div class="container">
      <!-- Main hero unit for a primary marketing message or call to action -->

    <div class="hero-unit">
      <table class="table table-hover">
      <th>Folio</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Revisar encuesta</th>
      <!-- iterar sobre las encuestas -->
      {% for encuesta in encuestas %}
        <tr> <!-- inicia el renglon -->
        	<td>{{encuesta.folio}}</td> <!-- insertar el folio de la encuesta -->
          <td>{{encuesta.inscrito.estudiante.nombre}}</td>
          <td>{{encuesta.inscrito.estudiante.apellido}}</td>
          <td>
          <a href="/revisar_encuesta/{{encuesta.id}}">Revisar</a>
          <!-- <div id="icons">
            <i class="icon-search"></i>
          </div> -->
          </td>
        </tr> <!-- cerrar el renglon -->
      {% endfor %}
      </table>
    </div>
</div> <!-- /container -->
 
 {% endblock %}

templates/encuestas/revisar_encuesta.html
{% extends "boardskin/boardskinbase.html" %}
{% load crispy_forms_tags %}

 {% block style %}
 
 <link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
 {% endblock %}
 
 {% block script %}
 
 <script src="{{ STATIC_URL }}JS/jquery-1.9.1.min.js"></script>
 <script src="{{ STATIC_URL }}JS/jquery-ui-1.10.1.custom.js" type="text/javascript" charset="utf-8"></script>
 
 <script type="text/javascript">
    $(document).ready(function() {
      $('#id_folio').attr('readonly', true);
    });
  </script>
 
 {% endblock %}
 
 {% block content %}
 
<div class="section-header">
  <h1>Revisar Encuesta</h1> 
</div>

 <div class="container-fluid ">
  <div class="row-fluid">
    <div class="span12">
      <div class="widget">
      <!-- Main hero unit for a primary marketing message or call to action -->
        {{ forma.errors }}
       	{% crispy forma %}       	
      <hr>
     </div>
   </div>
 </div>
</div>
 
{% endblock %}