SAT/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^$', 'app.views.muestra', name='muestra'),
    # url(r'^SAT/', include('SAT.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),

     # Url exitoso
     url(r'^login/$',  login),
     url(r'^logout/', 'app.views.logout_view', name = 'logout_view'),
     url(r'^success/$', 'app.views.success', name='success_muestra'),
     
     # Urls para el manejo de estudiantes.
     url(r'^estudiante/$', 'app.views.estudiante', name='estudiante'),
     url(r'^alta_estudiante/$', 'app.views.alta_estudiante', name='alta_estudiante'),
     url(r'^edita_estudiante/(\d+)/$', 'app.views.edita_estudiante', name='edita_estudiante'),
     url(r'^perfil_estudiante/(\d+)/$', 'app.views.perfil_estudiante', name='perfil_estudiante'),
     url(r'^evaluar_estudiante/(\d+)/$', 'app.views.evaluar_estudiante', name='evaluar_estudiante'),

     # Urls para el manejo de muestras.
     url(r'^muestra/$', 'app.views.muestra', name='muestra'),
     url(r'^seleccion_muestra/$', 'app.views.seleccion_muestra', name='seleccion_muestra'),
     url(r'^perfil_muestra/(\d+)/$', 'app.views.perfil_muestra', name='perfil_muestra'),
     url(r'^alta_muestra/$', 'app.views.alta_muestra', name='alta_muestra'),
     url(r'^eliminar_muestra/(\d+)/$', 'app.views.eliminar_muestra', name='eliminar_muestra'),
     
     # Url para crear cartas de notificacion
     # url(r'^carta_notificacion/(?P<string>[\w\-]+)', 'app.views.obtener_carta', name='obtener_carta'),
     url(r'^carta_notificacion/(\d+)/(\d+)/$', 'app.views.obtener_carta', name='obtener_carta'),
     
     # Urls para iniciar y cerrar sesion.
     url(r'^accounts/login/$',  login),
     url(r'^accounts/logout/$',  logout),
     
     # Urls para mostrar vista de encuesta.
     url(r'^autenticacion_encuesta/$', 'app.views.autenticacion_encuesta', name='autenticacion_encuesta'),
     url(r'^aplicacion_encuesta/(\w+)/$', 'app.views.aplicacion_encuesta', name='aplicacion_encuesta'),
     # url(r'^encuesta_agradecimiento/$', 'app.views.encuesta_agradecimiento', name='encuesta_agradecimiento'),
     
     # Urls para mostrar lista de encuestas contestadas.
     url(r'^encuestas_contestadas/$', 'app.views.encuestas_contestadas', name='encuestas_contestadas'),
     url(r'^revisar_encuesta/(\d+)/$', 'app.views.revisar_encuesta', name='revisar_encuesta'),

     # Urls para mostrar reportes en highcharts.
     url(r'^reportes/$', 'app.views.reportes', name='reportes'),
     
     # Url para subir el CSV
     url(r'^subir_csv/$', 'app.views.subir_csv', name='subir_csv'),
     url(r'^subir_csv/success/$', 'app.views.subir_csv_success', name='subir_csv_success'),
)

# Add the static files pattern to the url.
urlpatterns += staticfiles_urlpatterns()

app/forms.py
# -*- coding: utf-8 -*
from app.models import *
from django import forms
from django.forms import ModelForm 
from crispy_forms.helper import FormHelper,reverse
from crispy_forms.layout import *

my_default_errors = {
    'required': 'Se requiere este campo.',
    'invalid': 'Este campo es invalido.'
}

ESTADO_INSTITUCION = (
    ('0','Activo'),
    ('1','Inactivo'),
)

TIPO_SELECCION = (
    ('0','Aleatoria'),
    ('1','Dirigida'),
)

TIPO_DROGA = (
    ('0', 'Marihuana'),
    ('1', 'Cocaína'),
    ('2', 'Metanfetaminas | Anfetaminas'),
    ('3', 'Alucinógenos'),
    ('4', 'Opiáceos'),
    ('5', 'Otro'),
)

ESTADO_ANTIDOPING = (
    ('0','Iniciado'),
    ('1','1era. Notificación recibida'),
    ('2','2da. Notificación recibida'),
    ('3','Encuesta realizada'),
    ('4','Prueba realizada'),
    ('5','Cerrado'),
)

SI_NO = (
    ('0','Sí'),
    ('1','No'),
)

ALCOHOL_FRECUENCIA = (
    ('0','No consumo'),
    ('1','Una vez a la semana o menos'),
    ('2','Dos veces a la semana'),
    ('3','Más de dos veces por semana'),
)

TABACO_FRECUENCIA = (
    ('0','No consumo'),
    ('1','Menos de 5 cigarros al día'),
    ('2','De 5 a 10 cigarros al día'),
    ('3','De 10 cigarrillos a una cajetilla al día'),
    ('4','Más de una cajetilla al día'),
)

SI_NO_2 = (
    ('0','Sí'),
    ('1','No (Pasa a la pregunta 8)'),
)

QUIEN_OFRECIDO = (
    ('0','Un compañero de la escuela'),
    ('1','Un amigo'),
    ('2','Un vecino'),
    ('3','Un conocido'),
    ('4','Un familiar'),
    ('5','Otro'),
)

DONDE_OFRECIDO = (
    ('0','En un antro, bar, concierto o fiesta'),
    ('1','En un viaje al extranjero'),
    ('2','En casa de algún amigo o compañero'),
    ('3','En la escuela'),
    ('4','En la calle'),
    ('5','Otro'),
)

QUE_OFRECIDO_CONSUMIDO = (
    ('0','Marihuana'),
    ('1','Cocaína'),
    ('2','Anfetaminas, Metanfetaminas'),
    ('3','Alucinógenos'),
    ('4','Opiáceos'),
    ('5','Otro'),
)

SI_NO_3 = (
    ('0','Sí'),
    ('1','No (Pasa a la pregunta 13)'),
)

ULTIMO_CONSUMIDO = (
    ('0','En los últimos 30 días'),
    ('1','Hace más de un mes y menos de cinco meses'),
    ('2','Hace más de seis meses'),
)

QUIEN_OFRECIDO = (
    ('0','Un compañero de la escuela'),
    ('1','Un amigo'),
    ('2','Un vecino'),
    ('3','Un conocido'),
    ('4','Un familiar'),
    ('5','Otro'),
)

LUGAR_CONSUMIDO = (
    ('0','En un antro, bar, concierto o fiesta'),
    ('1','En un viaje al extranjero'),
    ('2','En casa de algún amigo o compañero'),
    ('3','En la escuela'),
    ('4','En la calle'),
    ('5','Otro'),
)

COLOR = (
    # ('0','Gris'),
    ('1','Verde'),
    ('2','Amarillo'),
    ('3','Naranja'),
    ('4','Rojo'),
    ('5','Negro'),
)

DIA_SEMANA = (
    ('lunes', 'Lunes'),
    ('martes', 'Martes'),
    ('miercoles', 'Miércoles'),
    ('jueves', 'Jueves'),
    ('viernes', 'Viernes'),
    ('sabado', 'Sábado'),
  )

HORARIO = (
    ('7', '7:00'),
    ('7+', '7:30'),
    ('8', '8:00'),
    ('8+', '8:30'),
    ('9', '9:00'),
    ('9+', '9:30'),
    ('10', '10:00'),
    ('10+', '10:30'),
    ('11', '11:00'),
    ('11+', '11:30'),
    ('12', '12:00'),
    ('12+', '12:30'),
    ('13', '13:00'),
    ('13+', '13:30'),
    ('14', '14:00'),
    ('14+', '14:30'),
    ('15', '15:00'),
    ('15+', '15:30'),
    ('16', '16:00'),
    ('16+', '16:30'),
    ('17', '17:00'),
    ('17+', '17:30'),
    ('18', '18:00'),
    ('18+', '18:30'),
    ('19', '19:00'),
    ('19+', '19:30'),
    ('20', '20:00'),
    ('20+', '20:30'),
    ('21', '21:00'),
    ('21+', '21:30'),
    ('22', '22:00'),
  )

RESULTADO_ANTIDOPING = (
    ('0', 'Negativo'),
    ('1', 'Positivo'),
  )

class AltaEstudiante(ModelForm):
  matricula = forms.DecimalField(required = True,label="Matricula")
  nombre = forms.CharField(error_messages=my_default_errors,label="Nombre",required=True)
  apellido = forms.CharField(error_messages=my_default_errors,label="Apellido",required=True)
  correo = forms.CharField(error_messages=my_default_errors,label="Correo",required=False)
  telefono = forms.CharField(required = False,label="Telefono")
  celular = forms.CharField(required = False,label="Celular")
  color = forms.ChoiceField(error_messages=my_default_errors,choices=COLOR)
  estado_institucion = forms.ChoiceField(error_messages=my_default_errors,choices=ESTADO_INSTITUCION)
  
  class Meta:
    model = Estudiante
    exclude = ('padre','madre')
        
  def __init__(self, *args, **kwargs):
      self.helper = FormHelper()
      self.helper.form_id = 'id-AltaEstudiante'
      self.helper.form_class = 'blueForms'
      self.helper.form_method = 'POST'
      self.helper.layout = Layout(
	Div(
	Div(
	    'matricula',
	    'nombre',
	    'apellido',
	    'correo',
	    'telefono',
	    'celular',
	    css_class='span3'),
	Div('color',
	    'estado_institucion',
	    css_class='span3'),css_class='row-fluid'),
	ButtonHolder(
	    Submit('submit', 'Crear', css_class='btn-success')
	))
      super(AltaEstudiante, self).__init__(*args, **kwargs)
  
class CrearAntidoping(ModelForm):
  nombre = forms.CharField(error_messages=my_default_errors,label="Nombre")
  tamano_muestra = forms.DecimalField(label="Tamaño de la muestra (máximo)")
  notas = forms.CharField(widget=forms.Textarea, error_messages=my_default_errors, label="Notas", required=False)
  seleccion_alumnos = forms.CharField(widget=forms.Textarea, required=False, label="Selección de alumnos")
  seleccion_grupos = forms.CharField(widget=forms.Textarea, required=False, label="Selección de grupos")
  dia = forms.ChoiceField(error_messages=my_default_errors,choices=DIA_SEMANA, label="Día")
  inicio = forms.ChoiceField(error_messages=my_default_errors,choices=HORARIO)
  fin = forms.ChoiceField(error_messages=my_default_errors,choices=HORARIO)
  
  class Meta:
    model = Antidoping
    exclude = ('muestra_inicio', 'antidoping_inicio', 'antidoping_fin', 'muestra_fin', 'estudianteMuestra', 'estado_antidoping')
        
  def __init__(self, *args, **kwargs):
      self.helper = FormHelper()
      self.helper.form_id = 'id-CrearAntidoping'
      self.helper.form_class = 'blueForms'
      self.helper.form_method = 'POST'
      self.helper.form_action = 'seleccion_muestra'
      self.helper.layout = Layout(
	Div(
	Div(
	    'nombre',
      'tamano_muestra',
      'dia',
      'seleccion_alumnos',
	    css_class='span3'
      ),
	Div(
      'inicio',
      'fin',
	    css_class='span3'
      ),
	Div(
	    'notas',
	    'seleccion_grupos',
	    css_class='span3'),css_class='row-fluid'),
	ButtonHolder(
	    Submit('submit', 'Crear', css_class='btn-success')
	))
      super(CrearAntidoping, self).__init__(*args, **kwargs)

# Esta forma se encarga de evaluar el resultado estudiante para cada antidoping.

class EvaluaEstudiante(ModelForm):
  tipo_droga = forms.MultipleChoiceField(required = False, widget=forms.CheckboxSelectMultiple, choices=TIPO_DROGA)
  estado = forms.ChoiceField(required = False, error_messages=my_default_errors,choices=ESTADO_ANTIDOPING)
  tipo_seleccion = forms.ChoiceField(required = False, error_messages=my_default_errors,choices=TIPO_SELECCION)
  resultado = forms.ChoiceField(required = False, error_messages=my_default_errors,choices=RESULTADO_ANTIDOPING)
  notas = forms.CharField(required = False, widget=forms.Textarea, error_messages=my_default_errors, label="Notas")

  class Meta:
    model = EstudianteMuestra
    exclude = ('folio','antidoping','inscrito','respuestas')
        
  def __init__(self, *args, **kwargs):
      self.helper = FormHelper()
      self.helper.form_id = 'id-EvaluaEstudiante'
      self.helper.form_class = 'blueForms'
      self.helper.form_method = 'POST'
      self.helper.form_action = ''
      self.helper.layout = Layout(
  Div(
  Div(
      'notificacion',
      'tipo_droga',
      css_class='span3'),
  Div(
      'tipo_seleccion',
      'estado',
      'resultado',
      css_class='span3'),
  Div(
      'notas',
      css_class='span3'),css_class='row-fluid'),
  ButtonHolder(
      Submit('submit', 'Guardar', css_class='btn-success')
  ))
      super(EvaluaEstudiante, self).__init__(*args, **kwargs)

class AplicacionEncuesta(ModelForm):
  folio = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}), error_messages=my_default_errors, label="Folio", required=False)
  medicamento_consumido = forms.ChoiceField(widget=forms.RadioSelect(), choices=SI_NO, label="1. ¿Actualmente consumes algún medicamento?",required=False)
  medicamento_consumido_paraque = forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'cols':40}), label="Si respondiste 'Sí', ¿cuál y para qué?", required = False)
  alcohol_frecuencia = forms.ChoiceField(widget=forms.RadioSelect(), choices=ALCOHOL_FRECUENCIA, label="2. ¿Con qué frecuencia consumes bebidas alcohólicas?",required=False)
  tabaco_frecuencia = forms.ChoiceField(widget=forms.RadioSelect(), choices=TABACO_FRECUENCIA, label="3. ¿Con qué frecuencia consumes cigarros de tabaco?",required=False)
  droga_ofrecido = forms.ChoiceField(widget=forms.RadioSelect(), choices=SI_NO_2, label="4. ¿Ten han ofrecido alguna vez alguna droga ilegal?",required=False)
  quien_ofrecido = forms.ChoiceField(widget=forms.RadioSelect(), choices=QUIEN_OFRECIDO, label="5. ¿Quién te ha ofrecido?",required=False)
  quien_ofrecido_otro = forms.CharField(widget=forms.TextInput(), label="Si responsite 'Otro' especifica quién", required=False)
  donde_ofrecido = forms.ChoiceField(widget=forms.RadioSelect(), choices=DONDE_OFRECIDO, label="6. ¿En dónde te han ofrecido?",required=False)
  donde_ofrecido_otro = forms.CharField(widget=forms.TextInput(), label="Si responsite 'Otro' especifica dónde", required=False)  
  que_ofrecido = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=QUE_OFRECIDO_CONSUMIDO, label="7. ¿Qué te ofrecieron? (Puedes seleccionar más de una opción)", required = False)
  que_ofrecido_otro = forms.CharField(widget=forms.TextInput(), label="Si responsite 'Otro' especifica qué", required=False)

templates/home/muestra/muestra.html
{% extends "boardskin/boardskinbase.html" %}
{% load crispy_forms_tags %}
{% load antidoping_extras %}
{% block antidoping %}current{% endblock %}



{% block style %}

<link href="{{ STATIC_URL }}CSS/tag-it.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}CSS/jquery.tagsinput.css" rel="stylesheet" type="text/css">
<style type="text/css">
#icons{
  float:right;
}
</style>

{% endblock %}

{% block script %}

<script src="{{ STATIC_URL }}JS/jquery.tagsinput.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/highcharts.js"></script>
<script type="text/javascript" language="javascript" src="{{ STATIC_URL }}JS/boostrap-tab.js"></script>

{% endblock %}

{% block content %}

<div class="section-header">
    <h1>Antidoping</h1> 
</div>

<div class="container-fluid ">
    <div class="row-fluid">
        <a href="/seleccion_muestra">
          <input type="button" class="btn btn-flat btn-blue no-radius" value="Nuevo"></button>
      </a>
  </div>
</div>
<br />
<div class="container-fluid ">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget">
              <table class="table table-striped table-bordered">
                <tr>
                    <th>Nombre del Antidoping</th>
                    <th>Fecha de creación</th>
                    <th>Estado</th>
                </tr>
                {% for antidoping in antidopings %}
                <tr>
                    <td>
                      <a href="/perfil_muestra/{{antidoping.id}}">{{antidoping.nombre}}</a>
                      <div id="icons"><a href="/eliminar_muestra/{{antidoping.id}}"><i class="icon-trash"></i></a></div>
                  </td>
                  <td>{{antidoping.antidoping_inicio}}</td>
                  <td>{{antidoping.estado_antidoping|estado}}</td>
              </tr>
              {% endfor %}
          </table>
      </div>
  </div>
</div>
</div>


<br />




{% endblock %}

templates/home/muestra/perfil_muestra.html
{% extends "boardskin/boardskinbase.html" %}
{% load crispy_forms_tags %}
{% load antidoping_extras %}
{% block antidoping %}current{% endblock %}

{% block style %}

<link href="{{ STATIC_URL }}CSS/tag-it.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
<style type="text/css">
#icons{
  float:right;
}
.table-nonfluid {
 width: auto;
 border:0px;
}


#icons{
  float:right;
}

ul {
    margin: 20px;
}

.input-color {
    position: relative;
}
.input-color input {
    padding-left: 20px;
    padding-right: 100px;
}
.input-color .color-box {
    width: 12px;
    height: 12px;
    display: inline-block;
    background-color: #ccc;
    position: relative;
    left: 0px;
    top:1px; 
}


</style>

{% endblock %}

{% block script %}
<script>

$(document).ready(function() {
 $('.notificacion').click(function(id) {
  var $id = parseInt(this.id.substring(4));
  window.location.href = ("/carta_notificacion/{{antidoping.id}}/"+$id);
});
});

</script>

{% endblock %}

{% block sidebar %}


<div class="statistic-list-icon  widget">
  <div class="widget-title">
    <h3>Estatus Antidoping</h3>
  </div>
      <ul class="listing">
          <li>
            <h4>{{antidoping|contar_objetos:0}}</h4>
            <p class="sub">Iniciado</p>
          </li>
          <li>
            <h4>{{antidoping|contar_objetos:1}}</h4>
            <p class="sub">Primera Notificación</p>
          </li>
          <li>
            <h4>{{antidoping|contar_objetos:2}}</h4>
            <p class="sub">Segunda Notificación</p>
          </li>

  </div>
<div class="statistic-list-icon  widget">
  <div class="widget-title">
    <h3>Resultados</h3>
  </div>
      <ul class="listing">
          <li>
            <h4>{{antidoping|negativos}}</h4>
            <p class="sub">Negativos</p>
          </li>
          <li>
            <h4>{{antidoping|positivos}}</h4>
            <p class="sub">Positivos</p>
          </li>
        </ul>
      </div>


<div class="statistic-list-icon  widget">
  <div class="widget-title">
    <h3>Generar Notificaciones</h3>
  </div>
      <ul class="listing">
          <li>
            <button type="button" id="not_1" class="btn btn-flat btn-blue no-radius notificacion">Primera Notificación</button>
          </li>
          <li>
            <button type="button" id="not_2" class="btn btn-flat btn-blue no-radius notificacion">Segunda Notificación</button>
          </li>
          <li>
            <button type="button" id="not_3" class="btn btn-flat btn-blue no-radius btn-danger notificacion">No acudieron</button>
          </li>
  </div>

{% endblock %}

{% block content %}
<div class="section-header">
  <h1>{{antidoping.nombre}}</h1> 
</div>

<div class="container-fluid ">
  <div class="row-fluid">
    <div class="span12">
      <div class="widget">
      <h4>{{antidoping|contar_total}} Alumnos</h4>

      <table class="table table-striped table-bordered" style="margin-top:10px;">
        <tr>
         <th>Matricula</th>
         <th>Nombre</th>
         <th>Apellido</th>
         <th>Estado</th>
         <th>Resultado</th>
         <th>Encuesta</th>
         <th>Adicional</th>
       </tr>
       {% for a,b in alumnos %}
       <tr>
         <td>
        <div class="input-color">
          <div class="color-box" style="background-color: {{a.color|color}};"></div>
          <a href="/perfil_estudiante/{{a.matricula}}">{{a.matricula}}</a>
        
          <div id="icons">
            <a href="/edita_estudiante/{{a.matricula}}"><i class="icon-pencil"></i></a>
          </div>
          </div>
        </td>
        <td>{{a.nombre}}</td>
        <td>{{a.apellido}}</td>
        <td>{{b.estado|estado}}</td>
        <td>{{b.resultado|resultado}}</td>
        {% if b.respuestas %} 
        <td><a href="/revisar_encuesta/{{b.id}}">{{b.folio}}</a></td> 
        {% else %}
        <td>{{b.folio}}</td> 
        {% endif %}
        <td><a href="/evaluar_estudiante/{{b.id}}">Editar</a></td>
      </tr>
      {% endfor %}

    </table>
    <h4>Grupos</h4>
    <table class="table table-striped table-bordered">
      <tr>
       <th>CRN</th>
       <th>Clase Id</th>
       <th>Profesor</th>
     </tr>
     {% for g in grupos %}
     <tr>
       <td>{{g.crn}}</td>
       <td>{{g.clase.clave_materia}}</td>
       <td>{{g.profesor}}</td>
     </tr>
     {% endfor %}
   </table>

   <p>Notas :
    {{antidoping.notas}}
  </p>

</div>
</div>
</div>
</div>
{% endblock %}

templates/home/muestra/seleccion_muestra.html
{% extends "boardskin/boardskinbase.html" %}
{% load crispy_forms_tags %}
{% block antidoping %}current{% endblock %}

 {% block style %}
 
 <link href="{{ STATIC_URL }}CSS/tag-it.css" rel="stylesheet" type="text/css">
 <link href="{{ STATIC_URL }}CSS/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css">
 <link href="{{ STATIC_URL }}CSS/jquery.tagsinput.css" rel="stylesheet" type="text/css">
 <style>
 #id_notas{
  min-width: 300px;
  max-height: 170px;


 }
 </style>
 {% endblock %}
 
 {% block script %}
 
 <script src="{{ STATIC_URL }}JS/jquery.tagsinput.js" type="text/javascript" charset="utf-8"></script>
 
<script type="text/javascript">

    
    $(document).ready(function() {
      $('#id_seleccion_alumnos').tagsInput();   
      $('#id_seleccion_grupos').tagsInput(); 
    });

</script>
 
 {% endblock %}
 
 {% block content %}

 <div class="section-header">
    <h1>Seleccionar alumnos para la muestra</h1> 
  </div>
 
 <!-- <div class="container"> -->
 <div class="container-fluid ">
    <div class="row-fluid">
    <div class="span12">
    <div class="widget">
      <!-- Main hero unit for a primary marketing message or call to action -->
      <!-- <div class="hero-unit"> -->
        {{ forma.errors }}
       	{% crispy forma %}       	
      <!-- </div> /hero-unit -->
    </div> <!-- /container -->
  </div>
</div>
</div>
 
 {% endblock %}